package com.leonard.web_authn.shared.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {
    NOT_FOUND("ERR_000001", HttpStatus.NOT_FOUND),
    INVALID_REQUEST("ERR_000002", HttpStatus.BAD_REQUEST),
    EMAIL_REGISTERED("ERR_000003", HttpStatus.CONFLICT),
    CHALLENGE_NOT_FOUND("ERR_000004", HttpStatus.NOT_FOUND),
    CHALLENGE_EXPIRED("ERR_000005", HttpStatus.BAD_REQUEST),
    CHALLENGE_ALREADY_USED("ERR_000006", HttpStatus.BAD_REQUEST),
    CREDENTIAL_VERIFICATION_FAILED("ERR_000007", HttpStatus.BAD_REQUEST),
    USER_NOT_FOUND("ERR_000008", HttpStatus.NOT_FOUND),
    CREDENTIAL_NOT_FOUND("ERR_000009", HttpStatus.NOT_FOUND),
    SIGN_COUNT_INVALID("ERR_000010", HttpStatus.BAD_REQUEST),
    USERNAME_REGISTERED("ERR_000011", HttpStatus.CONFLICT),
    CREDENTIAL_ALREADY_REGISTERED("ERR_000012", HttpStatus.CONFLICT),
    CHALLENGE_OPERATION_TYPE_MISMATCH("ERR_000013", HttpStatus.BAD_REQUEST),
    USER_INACTIVE("ERR_000014", HttpStatus.FORBIDDEN),
    CREDENTIAL_USER_MISMATCH("ERR_000015", HttpStatus.BAD_REQUEST),
    RATE_LIMIT_EXCEEDED("ERR_000020", HttpStatus.TOO_MANY_REQUESTS),
    CANNOT_DELETE_LAST_PASSKEY("ERR_000021", HttpStatus.BAD_REQUEST),
    INVALID_RECOVERY_CODE("ERR_000022", HttpStatus.BAD_REQUEST),
    RECOVERY_CODE_EXPIRED("ERR_000023", HttpStatus.BAD_REQUEST),
    RECOVERY_CODE_ALREADY_USED("ERR_000024", HttpStatus.BAD_REQUEST),
    ACCOUNT_LOCKED("ERR_000025", HttpStatus.FORBIDDEN),
    SESSION_EXPIRED("ERR_000026", HttpStatus.UNAUTHORIZED),
    INVALID_REFRESH_TOKEN("ERR_000027", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED("ERR_000028", HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED("ERR_000030", HttpStatus.FORBIDDEN),
    ROLE_NOT_FOUND("ERR_000031", HttpStatus.NOT_FOUND),
    ROLE_ALREADY_ASSIGNED("ERR_000032", HttpStatus.CONFLICT),
    CANNOT_REMOVE_LAST_ADMIN("ERR_000033", HttpStatus.BAD_REQUEST);

    ErrorCode(String code, HttpStatus statusCode) {
        this.code = code;
        this.statusCode = statusCode;
    }

    private final String code;
    private final HttpStatus statusCode;
}
